# Generated by Django 4.2.6 on 2023-10-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_customuser_referrer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
