# Generated by Django 4.2.6 on 2023-10-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='otp_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
