# Generated by Django 4.2.6 on 2023-10-29 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_otpmodel_otp_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 29, 22, 17, 11, 40287, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
