# Generated by Django 4.2.7 on 2023-11-11 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_remove_customerdetails_bpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 11, 2, 16, 38, 330557, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
