# Generated by Django 4.2.7 on 2023-11-03 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(choices=[('Real Asset', 'Real Asset'), ('Real Banking', 'Real Banking'), ('Real Project', 'Real Project')], max_length=200, null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price_per_slot', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('amount', models.CharField(max_length=255, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slots_available', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms_and_condition', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Property',
            },
        ),
    ]
