# Generated by Django 4.2.7 on 2023-11-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/property/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/property/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/property/'),
        ),
    ]
