# Generated by Django 4.2.7 on 2023-11-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0008_alter_otpmodel_otp_expire_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.customerdetails')),
            ],
        ),
    ]
